language: python
python:
        - "3.5"
        - "3.6"
install:
        - pip install -r requirements.txt

script:
        pytest fleepbot/test/tests.py

deploy:
        provider: script
        script: sh .travis/deploy.sh
        on:
                branch: master
                python: "3.5"
