language: python
python:
        - "3.5"
        - "3.6"

env:
    global:
        - NAME=FleepBot
        - TRAVIS_DIR=.travis/
        - LOCAL_DEPLOY_SCRIPT=local_deploy.sh
        - PATH_TO_RUN_SCRIPT=fleepbot
        - RUN_SCRIPT=fleepbot.py

install:
        - pip install -r requirements.txt

script:
        pytest fleepbot/test/tests.py

deploy:
     -  provider: script
        script: bash .travis/deploy.sh
        on:
                branch: master
                python: '3.5'

     -  provider: script
        script: bash .travis/deploy.sh
        on:
                branch: develop
                python: '3.5'
